// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: llbuild3/core/Artifact.proto
// Protobuf C++ Version: 5.27.2

#include "llbuild3/core/Artifact.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace llbuild3 {
namespace core {

inline constexpr ListObject::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : entry_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ListObject::ListObject(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ListObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListObjectDefaultTypeInternal() {}
  union {
    ListObject _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListObjectDefaultTypeInternal _ListObject_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR DictObject_ContentsEntry_DoNotUse::DictObject_ContentsEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct DictObject_ContentsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DictObject_ContentsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DictObject_ContentsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    DictObject_ContentsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DictObject_ContentsEntry_DoNotUseDefaultTypeInternal _DictObject_ContentsEntry_DoNotUse_default_instance_;

inline constexpr DictObject::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : contents_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DictObject::DictObject(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DictObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DictObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DictObjectDefaultTypeInternal() {}
  union {
    DictObject _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DictObjectDefaultTypeInternal _DictObject_default_instance_;

inline constexpr Artifact::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        label_{nullptr},
        type_{static_cast< ::llbuild3::core::ArtifactType >(0)},
        value_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Artifact::Artifact(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ArtifactDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArtifactDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArtifactDefaultTypeInternal() {}
  union {
    Artifact _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArtifactDefaultTypeInternal _Artifact_default_instance_;
}  // namespace core
}  // namespace llbuild3
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_llbuild3_2fcore_2fArtifact_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_llbuild3_2fcore_2fArtifact_2eproto = nullptr;
const ::uint32_t
    TableStruct_llbuild3_2fcore_2fArtifact_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::DictObject_ContentsEntry_DoNotUse, _has_bits_),
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::DictObject_ContentsEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::DictObject_ContentsEntry_DoNotUse, key_),
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::DictObject_ContentsEntry_DoNotUse, value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::DictObject, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::DictObject, _impl_.contents_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::ListObject, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::ListObject, _impl_.entry_),
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::Artifact, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::Artifact, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::Artifact, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::Artifact, _impl_.label_),
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::Artifact, _impl_.type_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::llbuild3::core::Artifact, _impl_.value_),
        0,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::llbuild3::core::DictObject_ContentsEntry_DoNotUse)},
        {12, -1, -1, sizeof(::llbuild3::core::DictObject)},
        {21, -1, -1, sizeof(::llbuild3::core::ListObject)},
        {30, 45, -1, sizeof(::llbuild3::core::Artifact)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::llbuild3::core::_DictObject_ContentsEntry_DoNotUse_default_instance_._instance,
    &::llbuild3::core::_DictObject_default_instance_._instance,
    &::llbuild3::core::_ListObject_default_instance_._instance,
    &::llbuild3::core::_Artifact_default_instance_._instance,
};
const char descriptor_table_protodef_llbuild3_2fcore_2fArtifact_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034llbuild3/core/Artifact.proto\022\rllbuild3"
    ".core\032\027llbuild3/core/CAS.proto\032\031llbuild3"
    "/core/Label.proto\"x\n\nDictObject\0229\n\010conte"
    "nts\030\003 \003(\0132\'.llbuild3.core.DictObject.Con"
    "tentsEntry\032/\n\rContentsEntry\022\013\n\003key\030\001 \001(\t"
    "\022\r\n\005value\030\002 \001(\t:\0028\001\"\033\n\nListObject\022\r\n\005ent"
    "ry\030\003 \003(\t\"\372\001\n\010Artifact\022#\n\005label\030\001 \001(\0132\024.l"
    "lbuild3.core.Label\022)\n\004type\030\002 \001(\0162\033.llbui"
    "ld3.core.ArtifactType\022/\n\tcasObject\030\003 \001(\013"
    "2\032.llbuild3.core.CASObjectIDH\000\022\016\n\004blob\030\004"
    " \001(\014H\000\022)\n\004dict\030\005 \001(\0132\031.llbuild3.core.Dic"
    "tObjectH\000\022)\n\004list\030\006 \001(\0132\031.llbuild3.core."
    "ListObjectH\000B\007\n\005value*V\n\014ArtifactType\022\010\n"
    "\004FILE\020\000\022\r\n\tDIRECTORY\020\001\022\010\n\004BLOB\020\002\022\010\n\004DICT"
    "\020\003\022\010\n\004LIST\020\004\022\017\n\013BUILD_GRAPH\020\005b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_llbuild3_2fcore_2fArtifact_2eproto_deps[2] =
    {
        &::descriptor_table_llbuild3_2fcore_2fCAS_2eproto,
        &::descriptor_table_llbuild3_2fcore_2fLabel_2eproto,
};
static ::absl::once_flag descriptor_table_llbuild3_2fcore_2fArtifact_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_llbuild3_2fcore_2fArtifact_2eproto = {
    false,
    false,
    597,
    descriptor_table_protodef_llbuild3_2fcore_2fArtifact_2eproto,
    "llbuild3/core/Artifact.proto",
    &descriptor_table_llbuild3_2fcore_2fArtifact_2eproto_once,
    descriptor_table_llbuild3_2fcore_2fArtifact_2eproto_deps,
    2,
    4,
    schemas,
    file_default_instances,
    TableStruct_llbuild3_2fcore_2fArtifact_2eproto::offsets,
    file_level_enum_descriptors_llbuild3_2fcore_2fArtifact_2eproto,
    file_level_service_descriptors_llbuild3_2fcore_2fArtifact_2eproto,
};
namespace llbuild3 {
namespace core {
const ::google::protobuf::EnumDescriptor* ArtifactType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_llbuild3_2fcore_2fArtifact_2eproto);
  return file_level_enum_descriptors_llbuild3_2fcore_2fArtifact_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ArtifactType_internal_data_[] = {
    393216u, 0u, };
bool ArtifactType_IsValid(int value) {
  return 0 <= value && value <= 5;
}
// ===================================================================

DictObject_ContentsEntry_DoNotUse::DictObject_ContentsEntry_DoNotUse() {}
DictObject_ContentsEntry_DoNotUse::DictObject_ContentsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
const ::google::protobuf::MessageLite::ClassData*
DictObject_ContentsEntry_DoNotUse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // tc_table
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(DictObject_ContentsEntry_DoNotUse, _cached_size_),
              false,
          },
          &DictObject_ContentsEntry_DoNotUse::MergeImpl,
          &DictObject_ContentsEntry_DoNotUse::kDescriptorMethods,
          &descriptor_table_llbuild3_2fcore_2fArtifact_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
// ===================================================================

class DictObject::_Internal {
 public:
};

DictObject::DictObject(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:llbuild3.core.DictObject)
}
inline PROTOBUF_NDEBUG_INLINE DictObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::llbuild3::core::DictObject& from_msg)
      : contents_{visibility, arena, from.contents_},
        _cached_size_{0} {}

DictObject::DictObject(
    ::google::protobuf::Arena* arena,
    const DictObject& from)
    : ::google::protobuf::Message(arena) {
  DictObject* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:llbuild3.core.DictObject)
}
inline PROTOBUF_NDEBUG_INLINE DictObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : contents_{visibility, arena},
        _cached_size_{0} {}

inline void DictObject::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DictObject::~DictObject() {
  // @@protoc_insertion_point(destructor:llbuild3.core.DictObject)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DictObject::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
DictObject::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(DictObject, _impl_._cached_size_),
              false,
          },
          &DictObject::MergeImpl,
          &DictObject::kDescriptorMethods,
          &descriptor_table_llbuild3_2fcore_2fArtifact_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 41, 2> DictObject::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967291,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_DictObject_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::llbuild3::core::DictObject>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<string, string> contents = 3;
    {PROTOBUF_FIELD_OFFSET(DictObject, _impl_.contents_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(DictObject()._impl_.contents_)>(
        1, 0, 0, 9,
        9)},
  }}, {{
    "\30\10\0\0\0\0\0\0"
    "llbuild3.core.DictObject"
    "contents"
  }},
};

PROTOBUF_NOINLINE void DictObject::Clear() {
// @@protoc_insertion_point(message_clear_start:llbuild3.core.DictObject)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.contents_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* DictObject::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:llbuild3.core.DictObject)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<string, string> contents = 3;
  if (!_internal_contents().empty()) {
    using MapType = ::google::protobuf::Map<std::string, std::string>;
    using WireHelper = _pbi::MapEntryFuncs<std::string, std::string,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_STRING>;
    const auto& field = _internal_contents();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            3, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "llbuild3.core.DictObject.contents");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "llbuild3.core.DictObject.contents");
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            3, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "llbuild3.core.DictObject.contents");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "llbuild3.core.DictObject.contents");
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llbuild3.core.DictObject)
  return target;
}

::size_t DictObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llbuild3.core.DictObject)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // map<string, string> contents = 3;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_contents_size());
  for (const auto& entry : _internal_contents()) {
    total_size += _pbi::MapEntryFuncs<std::string, std::string,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void DictObject::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DictObject*>(&to_msg);
  auto& from = static_cast<const DictObject&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:llbuild3.core.DictObject)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.contents_.MergeFrom(from._impl_.contents_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DictObject::CopyFrom(const DictObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llbuild3.core.DictObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DictObject::InternalSwap(DictObject* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.contents_.InternalSwap(&other->_impl_.contents_);
}

::google::protobuf::Metadata DictObject::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ListObject::_Internal {
 public:
};

ListObject::ListObject(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:llbuild3.core.ListObject)
}
inline PROTOBUF_NDEBUG_INLINE ListObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::llbuild3::core::ListObject& from_msg)
      : entry_{visibility, arena, from.entry_},
        _cached_size_{0} {}

ListObject::ListObject(
    ::google::protobuf::Arena* arena,
    const ListObject& from)
    : ::google::protobuf::Message(arena) {
  ListObject* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:llbuild3.core.ListObject)
}
inline PROTOBUF_NDEBUG_INLINE ListObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : entry_{visibility, arena},
        _cached_size_{0} {}

inline void ListObject::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ListObject::~ListObject() {
  // @@protoc_insertion_point(destructor:llbuild3.core.ListObject)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ListObject::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ListObject::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ListObject, _impl_._cached_size_),
              false,
          },
          &ListObject::MergeImpl,
          &ListObject::kDescriptorMethods,
          &descriptor_table_llbuild3_2fcore_2fArtifact_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 38, 2> ListObject::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967291,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ListObject_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::llbuild3::core::ListObject>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string entry = 3;
    {::_pbi::TcParser::FastUR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ListObject, _impl_.entry_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string entry = 3;
    {PROTOBUF_FIELD_OFFSET(ListObject, _impl_.entry_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\30\5\0\0\0\0\0\0"
    "llbuild3.core.ListObject"
    "entry"
  }},
};

PROTOBUF_NOINLINE void ListObject::Clear() {
// @@protoc_insertion_point(message_clear_start:llbuild3.core.ListObject)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entry_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ListObject::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:llbuild3.core.ListObject)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string entry = 3;
  for (int i = 0, n = this->_internal_entry_size(); i < n; ++i) {
    const auto& s = this->_internal_entry().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "llbuild3.core.ListObject.entry");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llbuild3.core.ListObject)
  return target;
}

::size_t ListObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llbuild3.core.ListObject)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated string entry = 3;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_entry().size());
  for (int i = 0, n = _internal_entry().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_entry().Get(i));
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ListObject::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListObject*>(&to_msg);
  auto& from = static_cast<const ListObject&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:llbuild3.core.ListObject)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_entry()->MergeFrom(from._internal_entry());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListObject::CopyFrom(const ListObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llbuild3.core.ListObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ListObject::InternalSwap(ListObject* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.entry_.InternalSwap(&other->_impl_.entry_);
}

::google::protobuf::Metadata ListObject::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Artifact::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Artifact>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Artifact, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::llbuild3::core::Artifact, _impl_._oneof_case_);
};

void Artifact::clear_label() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.label_ != nullptr) _impl_.label_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void Artifact::set_allocated_casobject(::llbuild3::core::CASObjectID* casobject) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_value();
  if (casobject) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(casobject)->GetArena();
    if (message_arena != submessage_arena) {
      casobject = ::google::protobuf::internal::GetOwnedMessage(message_arena, casobject, submessage_arena);
    }
    set_has_casobject();
    _impl_.value_.casobject_ = casobject;
  }
  // @@protoc_insertion_point(field_set_allocated:llbuild3.core.Artifact.casObject)
}
void Artifact::clear_casobject() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kCasObject) {
    if (GetArena() == nullptr) {
      delete _impl_.value_.casobject_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.value_.casobject_);
    }
    clear_has_value();
  }
}
void Artifact::set_allocated_dict(::llbuild3::core::DictObject* dict) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_value();
  if (dict) {
    ::google::protobuf::Arena* submessage_arena = dict->GetArena();
    if (message_arena != submessage_arena) {
      dict = ::google::protobuf::internal::GetOwnedMessage(message_arena, dict, submessage_arena);
    }
    set_has_dict();
    _impl_.value_.dict_ = dict;
  }
  // @@protoc_insertion_point(field_set_allocated:llbuild3.core.Artifact.dict)
}
void Artifact::set_allocated_list(::llbuild3::core::ListObject* list) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_value();
  if (list) {
    ::google::protobuf::Arena* submessage_arena = list->GetArena();
    if (message_arena != submessage_arena) {
      list = ::google::protobuf::internal::GetOwnedMessage(message_arena, list, submessage_arena);
    }
    set_has_list();
    _impl_.value_.list_ = list;
  }
  // @@protoc_insertion_point(field_set_allocated:llbuild3.core.Artifact.list)
}
Artifact::Artifact(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:llbuild3.core.Artifact)
}
inline PROTOBUF_NDEBUG_INLINE Artifact::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::llbuild3::core::Artifact& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        value_{},
        _oneof_case_{from._oneof_case_[0]} {}

Artifact::Artifact(
    ::google::protobuf::Arena* arena,
    const Artifact& from)
    : ::google::protobuf::Message(arena) {
  Artifact* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.label_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::llbuild3::core::Label>(
                              arena, *from._impl_.label_)
                        : nullptr;
  _impl_.type_ = from._impl_.type_;
  switch (value_case()) {
    case VALUE_NOT_SET:
      break;
      case kCasObject:
        _impl_.value_.casobject_ = ::google::protobuf::Message::CopyConstruct<::llbuild3::core::CASObjectID>(arena, *from._impl_.value_.casobject_);
        break;
      case kBlob:
        new (&_impl_.value_.blob_) decltype(_impl_.value_.blob_){arena, from._impl_.value_.blob_};
        break;
      case kDict:
        _impl_.value_.dict_ = ::google::protobuf::Message::CopyConstruct<::llbuild3::core::DictObject>(arena, *from._impl_.value_.dict_);
        break;
      case kList:
        _impl_.value_.list_ = ::google::protobuf::Message::CopyConstruct<::llbuild3::core::ListObject>(arena, *from._impl_.value_.list_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:llbuild3.core.Artifact)
}
inline PROTOBUF_NDEBUG_INLINE Artifact::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        value_{},
        _oneof_case_{} {}

inline void Artifact::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, label_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, label_) +
               sizeof(Impl_::type_));
}
Artifact::~Artifact() {
  // @@protoc_insertion_point(destructor:llbuild3.core.Artifact)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Artifact::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.label_;
  if (has_value()) {
    clear_value();
  }
  _impl_.~Impl_();
}

void Artifact::clear_value() {
// @@protoc_insertion_point(one_of_clear_start:llbuild3.core.Artifact)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (value_case()) {
    case kCasObject: {
      if (GetArena() == nullptr) {
        delete _impl_.value_.casobject_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.value_.casobject_);
      }
      break;
    }
    case kBlob: {
      _impl_.value_.blob_.Destroy();
      break;
    }
    case kDict: {
      if (GetArena() == nullptr) {
        delete _impl_.value_.dict_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.value_.dict_);
      }
      break;
    }
    case kList: {
      if (GetArena() == nullptr) {
        delete _impl_.value_.list_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.value_.list_);
      }
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}


const ::google::protobuf::MessageLite::ClassData*
Artifact::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Artifact, _impl_._cached_size_),
              false,
          },
          &Artifact::MergeImpl,
          &Artifact::kDescriptorMethods,
          &descriptor_table_llbuild3_2fcore_2fArtifact_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 6, 4, 0, 2> Artifact::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Artifact, _impl_._has_bits_),
    0, // no _extensions_
    6, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Artifact_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::llbuild3::core::Artifact>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .llbuild3.core.ArtifactType type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Artifact, _impl_.type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Artifact, _impl_.type_)}},
    // .llbuild3.core.Label label = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Artifact, _impl_.label_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .llbuild3.core.Label label = 1;
    {PROTOBUF_FIELD_OFFSET(Artifact, _impl_.label_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .llbuild3.core.ArtifactType type = 2;
    {PROTOBUF_FIELD_OFFSET(Artifact, _impl_.type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .llbuild3.core.CASObjectID casObject = 3;
    {PROTOBUF_FIELD_OFFSET(Artifact, _impl_.value_.casobject_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes blob = 4;
    {PROTOBUF_FIELD_OFFSET(Artifact, _impl_.value_.blob_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kBytes | ::_fl::kRepAString)},
    // .llbuild3.core.DictObject dict = 5;
    {PROTOBUF_FIELD_OFFSET(Artifact, _impl_.value_.dict_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .llbuild3.core.ListObject list = 6;
    {PROTOBUF_FIELD_OFFSET(Artifact, _impl_.value_.list_), _Internal::kOneofCaseOffset + 0, 3,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::llbuild3::core::Label>()},
    {::_pbi::TcParser::GetTable<::llbuild3::core::CASObjectID>()},
    {::_pbi::TcParser::GetTable<::llbuild3::core::DictObject>()},
    {::_pbi::TcParser::GetTable<::llbuild3::core::ListObject>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Artifact::Clear() {
// @@protoc_insertion_point(message_clear_start:llbuild3.core.Artifact)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.label_ != nullptr);
    _impl_.label_->Clear();
  }
  _impl_.type_ = 0;
  clear_value();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Artifact::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:llbuild3.core.Artifact)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .llbuild3.core.Label label = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.label_, _impl_.label_->GetCachedSize(), target, stream);
  }

  // .llbuild3.core.ArtifactType type = 2;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_type(), target);
  }

  switch (value_case()) {
    case kCasObject: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *_impl_.value_.casobject_, _impl_.value_.casobject_->GetCachedSize(), target, stream);
      break;
    }
    case kBlob: {
      const std::string& _s = this->_internal_blob();
      target = stream->WriteBytesMaybeAliased(4, _s, target);
      break;
    }
    case kDict: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, *_impl_.value_.dict_, _impl_.value_.dict_->GetCachedSize(), target, stream);
      break;
    }
    case kList: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          6, *_impl_.value_.list_, _impl_.value_.list_->GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llbuild3.core.Artifact)
  return target;
}

::size_t Artifact::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llbuild3.core.Artifact)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // .llbuild3.core.Label label = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.label_);
  }

  // .llbuild3.core.ArtifactType type = 2;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  switch (value_case()) {
    // .llbuild3.core.CASObjectID casObject = 3;
    case kCasObject: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.value_.casobject_);
      break;
    }
    // bytes blob = 4;
    case kBlob: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this->_internal_blob());
      break;
    }
    // .llbuild3.core.DictObject dict = 5;
    case kDict: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.value_.dict_);
      break;
    }
    // .llbuild3.core.ListObject list = 6;
    case kList: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.value_.list_);
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Artifact::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Artifact*>(&to_msg);
  auto& from = static_cast<const Artifact&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:llbuild3.core.Artifact)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.label_ != nullptr);
    if (_this->_impl_.label_ == nullptr) {
      _this->_impl_.label_ =
          ::google::protobuf::Message::CopyConstruct<::llbuild3::core::Label>(arena, *from._impl_.label_);
    } else {
      _this->_impl_.label_->MergeFrom(*from._impl_.label_);
    }
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_value();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kCasObject: {
        if (oneof_needs_init) {
          _this->_impl_.value_.casobject_ =
              ::google::protobuf::Message::CopyConstruct<::llbuild3::core::CASObjectID>(arena, *from._impl_.value_.casobject_);
        } else {
          _this->_impl_.value_.casobject_->MergeFrom(from._internal_casobject());
        }
        break;
      }
      case kBlob: {
        if (oneof_needs_init) {
          _this->_impl_.value_.blob_.InitDefault();
        }
        _this->_impl_.value_.blob_.Set(from._internal_blob(), arena);
        break;
      }
      case kDict: {
        if (oneof_needs_init) {
          _this->_impl_.value_.dict_ =
              ::google::protobuf::Message::CopyConstruct<::llbuild3::core::DictObject>(arena, *from._impl_.value_.dict_);
        } else {
          _this->_impl_.value_.dict_->MergeFrom(from._internal_dict());
        }
        break;
      }
      case kList: {
        if (oneof_needs_init) {
          _this->_impl_.value_.list_ =
              ::google::protobuf::Message::CopyConstruct<::llbuild3::core::ListObject>(arena, *from._impl_.value_.list_);
        } else {
          _this->_impl_.value_.list_->MergeFrom(from._internal_list());
        }
        break;
      }
      case VALUE_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Artifact::CopyFrom(const Artifact& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llbuild3.core.Artifact)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Artifact::InternalSwap(Artifact* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Artifact, _impl_.type_)
      + sizeof(Artifact::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(Artifact, _impl_.label_)>(
          reinterpret_cast<char*>(&_impl_.label_),
          reinterpret_cast<char*>(&other->_impl_.label_));
  swap(_impl_.value_, other->_impl_.value_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Artifact::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace llbuild3
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_llbuild3_2fcore_2fArtifact_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
