#!/bin/bash
set -eu

function usage() {
  echo "Usage: $0 VERSION"
}

if [[ $# -eq 0 ]]; then
  usage
  exit 1
fi

export LLBUILD_PODSPEC_VERSION="$1"
echo "Pushing llbuild.podspec to trunk with version $LLBUILD_PODSPEC_VERSION"
pod trunk push llbuild.podspec
