#!/usr/bin/env bash

set -e

# This script writes the Swift compiler version to a file. If the file is
# already present, it'll only update if the version has changed.

if ! [ $# -eq 2 ]; then
    echo "Usage: <compiler-path> <file-path>"
    exit
fi

SWIFTC=$1
FILEPATH=$2

VERSION="$($SWIFTC -version | tr -d '\n')"

if [[ -f $FILEPATH ]]; then
    FILECONTENT="$(cat $FILEPATH)"
    if [[ "$FILECONTENT" != "$VERSION" ]]; then
        echo $VERSION > $FILEPATH
    fi
else
    echo $VERSION > $FILEPATH
fi
