//===- ShellCommand.h -------------------------------------------*- C++ -*-===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2019 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See http://swift.org/LICENSE.txt for license information
// See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

#ifndef LLBUILD_BUILDSYSTEM_SHELLCOMMAND_H
#define LLBUILD_BUILDSYSTEM_SHELLCOMMAND_H

#include "llbuild/BuildSystem/BuildSystemHandlers.h"
#include "llbuild/BuildSystem/ExternalCommand.h"

#include "llbuild/Basic/ShellUtility.h"

#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/MemoryBuffer.h"

#include <atomic>
#include <string>
#include <vector>

namespace llbuild {
  namespace basic {
    class QueueJobContext;
  }
  namespace core {
    class Task;
  }
  
namespace buildsystem {

class BuildNode;
class BuildSystem;
class ExternalCommandHandler;

class ShellCommand : public ExternalCommand {
  /// The dependencies style to expect (in the `depsPath`).
  enum class DepsStyle {
    /// No discovered dependencies are in use.
    Unused = 0,
      
    /// "Makefile" style dependencies in the form typically generated by C
    /// compilers, wherein the dependencies of the first target are treated as
    /// dependencies of the command.
    Makefile,

    /// Darwin's DependencyInfo format.
    DependencyInfo,

    /// "Makefile" style dependencies in the form typically generated by C
    /// compilers, ignoring dependencies of all but the first output.
    MakefileIgnoringSubsequentOutputs,
  };
  
  /// The command line arguments.
  std::vector<StringRef> args;

  /// Arbitrary string used to *replace* the computed task signature.
  ///
  /// Deprecated: clients that need to keep an argument from contributing to the
  /// signature should mark it in `signatureIgnoredArgs` and let the signature be
  /// computed here, so that the command's identity is derived from the command
  /// itself rather than from a hash the client has to keep in sync.
  std::string signatureData;

  /// Indices into `args` of arguments that do not affect the command's outputs,
  /// and are therefore excluded from its signature.
  ///
  /// The client owns this knowledge, only it knows that, say, an index-store
  /// path changes nothing about the object file a compiler produces. Sorted
  /// strictly ascending; indices past the end of `args` have no effect.
  SmallVector<uint32_t, 4> signatureIgnoredArgs;

  /// Arbitrary string mixed *into* the computed task signature, for client state
  /// that is not visible in the command line or environment.
  std::string additionalSignatureData;

  /// The environment bindings specific to this command.
  ///
  /// If `envBase` is set these are layered over it, and are typically just the
  /// handful of per-file keys that distinguish this command from its siblings.
  /// Otherwise they are the whole environment. Empty with no base means the
  /// environment is inherited.
  SmallVector<std::pair<StringRef, StringRef>, 1> envOverrides;

  /// The shared environment table `envOverrides` is layered over, if any.
  ///
  /// Owned by the BuildDescription, which outlives this command.
  const EnvironmentBase* envBase = nullptr;
  
  /// The path to the dependency output file, if used.
  SmallVector<std::string, 1> depsPaths{};

  /// The style of dependencies used.
  DepsStyle depsStyle = DepsStyle::Unused;

  /// Whether to inherit the base environment.
  bool inheritEnv = true;

  /// Whether it is safe to interrupt (SIGINT) the tool during cancellation.
  bool canSafelyInterrupt = true;

  /// Working directory in which to spawn the external command
  std::string workingDirectory;

  /// Whether the control pipe is enabled for this command
  bool controlEnabled = true;

  /// The cached signature, once computed -- 0 is used as a sentinel value.
  mutable std::atomic<basic::CommandSignature> cachedSignature{ };

  /// The handler to use for this command, if present.
  ShellCommandHandler* handler;

  /// The handler state, if used.
  std::unique_ptr<HandlerState> handlerState;

  virtual void start(BuildSystem& system, core::TaskInterface) override;
  
  virtual basic::CommandSignature getSignature() const override;

  bool processDiscoveredDependencies(BuildSystem& system,
                                     core::TaskInterface ti,
                                     basic::QueueJobContext* context);
  
  bool processMakefileDiscoveredDependencies(BuildSystem& system,
                                             core::TaskInterface ti,
                                             basic::QueueJobContext* context,
                                             StringRef depsPath,
                                             llvm::MemoryBuffer* input,
                                             bool ignoreSubsequentOutputs);

  bool
  processDependencyInfoDiscoveredDependencies(BuildSystem& system,
                                              core::TaskInterface ti,
                                              basic::QueueJobContext* context,
                                              StringRef depsPath,
                                              llvm::MemoryBuffer* input);

public:
  using ExternalCommand::ExternalCommand;
  ShellCommand(StringRef name, bool controlEnabled) : ExternalCommand(name),
    controlEnabled(controlEnabled) { }

  virtual const std::vector<StringRef>& getArgs() const { return args; }

  /// The command's own environment bindings, which override those of any base.
  virtual const SmallVector<std::pair<StringRef, StringRef>, 1>&
  getEnvOverrides() const { return envOverrides; }

  /// The shared environment table this command's bindings layer over, if any.
  const EnvironmentBase* getEnvBase() const { return envBase; }

  /// Append the effective environment, the base composed with this command's
  /// own bindings, to `result`.
  ///
  /// Deliberately not cached: it is needed only when the command is about to
  /// spawn a process, so composing it on demand keeps a loaded build
  /// description down to what varies between commands. For a project whose
  /// script commands each carry a few thousand settings that is the difference
  /// between megabytes and hundreds of megabytes.
  void getEffectiveEnv(
      SmallVectorImpl<std::pair<StringRef, StringRef>>& result) const;

  bool getInheritEnv() const { return inheritEnv; }
  
  virtual void getShortDescription(SmallVectorImpl<char> &result) const override {
    llvm::raw_svector_ostream(result) << getDescription();
  }

  virtual void getVerboseDescription(SmallVectorImpl<char> &result) const override {
    llvm::raw_svector_ostream os(result);
    bool first = true;
    for (const auto& arg: args) {
      if (!first) os << " ";
      first = false;
      basic::appendShellEscapedString(os, arg);
    }
  }
  
  virtual bool configureAttribute(const ConfigureContext& ctx, StringRef name,
                                  StringRef value) override;
  
  virtual bool configureAttribute(const ConfigureContext& ctx, StringRef name,
                                  ArrayRef<StringRef> values) override;

  virtual bool configureAttribute(
      const ConfigureContext& ctx, StringRef name,
      ArrayRef<std::pair<StringRef, StringRef>> values) override;

  virtual bool configureEnvironmentBase(const ConfigureContext& ctx,
                                        const EnvironmentBase* base) override;


  // Shell command doesn't have any dynamic dependencies, so do nothing.
  void startExternalCommand(BuildSystem& system, core::TaskInterface) override {};

  // Not expecting any dependencies, so do nothing.
  void provideValueExternalCommand(
      BuildSystem& system,
      core::TaskInterface,
      uintptr_t inputID,
      const BuildValue& value) override {};

  virtual void executeExternalCommand(
      BuildSystem& system,
      core::TaskInterface ti,
      basic::QueueJobContext* context,
      llvm::Optional<basic::ProcessCompletionFn> completionFn) override;
};

}
}

#endif
